name: flutter_and_friends
description: The official Flutter & Friends conference app.
publish_to: none
version: 0.2.0+2

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.0
  pub_semver: ^2.1.4
  shorebird_code_push: ^1.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/speakers/
    - assets/sponsors/
    - shorebird.yaml
  uses-material-design: true
