name: flutter_and_friends
description: The official Flutter & Friends conference app.
publish_to: none
version: 1.2.0+18

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  pub_semver: ^2.1.4
  pusher_beams: ^1.1.1
  restart_app: ^1.2.1
  shorebird_code_push: ^1.1.4
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/
    - assets/activities/
    - assets/speakers/
    - assets/sponsors/
    - shorebird.yaml
  uses-material-design: true
