name: conference_repository
description: A Dart repository which manages the conference domain
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
