name: patch

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9].[0-9]+.[1-9]+" # e.g. v1.0.1, v1.0.2, v1.0.3, ...

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

jobs:
  patch-android:
    runs-on: ubuntu-latest

    name: ğŸ¤– Patch Android

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3

      - name: â˜•ï¸ Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: ğŸ¦ Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      - name: ğŸ” Decode Keystore
        run: echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/keystore.jks

      - name: ğŸ§© Shorebird Patch
        uses: shorebirdtech/shorebird-patch@v0
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        with:
          platform: android
          args: "--verbose --staging"

      - name: ğŸ“¦ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter_and_friends-${{ github.ref_name }}.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: ğŸ“¦ Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: flutter_and_friends-${{ github.ref_name }}.aab
          path: build/app/outputs/bundle/release/app-release.aab

  patch-ios:
    runs-on: macos-latest

    name: ğŸ Patch iOS

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¦ Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      - name: ğŸ§© Shorebird Patch
        uses: shorebirdtech/shorebird-patch@v0
        with:
          platform: ios
          args: "--staging"

      - name: ğŸ“¦ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-${{ github.ref_name }}
          patH: build/ios/ipa/flutter_and_friends.ipa
