name: patch

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[1-9]+" # e.g. v1.0.1, v1.0.2, v1.0.3, ...

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

jobs:
  patch-android:
    runs-on: ubuntu-latest

    name: ğŸ¤– Patch Android

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¦ Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      - name: ğŸ§© Shorebird Patch
        uses: shorebirdtech/shorebird-patch@v0
        with:
          platform: android
          args: "--artifact=apk --staging"

      - name: ğŸ“¦ Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-release-${{ github.ref_name }}
          patH: build/app/outputs/apk/release/app-release.apk

  patch-ios:
    runs-on: ubuntu-latest

    name: ğŸ Patch iOS

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¦ Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      - name: ğŸ§© Shorebird Patch
        uses: shorebirdtech/shorebird-patch@v0
        with:
          platform: ios
          args: "--staging"

      - name: ğŸ“¦ Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-release-${{ github.ref_name }}
          patH: build/ios/ipa/flutter_and_friends.ipa
